<?php
/**
 * Copyright (C) EC Brands Corporation - All Rights Reserved
 * Contact Licensing@ECInternet.com for use guidelines
 */
declare(strict_types=1);
?>

<?php /** @var \Magento\Sales\Block\Order\Info $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('Order Information')) ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?= $escaper->escapeHtml(__('Shipping Address')) ?></span></strong>
                <div class="box-content">
                    <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                </div>
            </div>

            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?= $escaper->escapeHtml(__('Shipping Method')) ?></span>
                </strong>
                <div class="box-content">
                <?php if ($_order->getShippingDescription()): ?>
                    <?= $escaper->escapeHtml($_order->getShippingDescription()) ?>
                <?php else: ?>
                    <?= $escaper->escapeHtml(__('No shipping information available')) ?>
                <?php endif; ?>

                <div class="tracking-numbers">
                    <?php $tracksCollection = $_order->getTracksCollection(); ?>
                    <?php if ($count = $tracksCollection->getSize()) { ?>
                        <?php $i = 1; ?>
                        <?php $_size = $tracksCollection->count(); ?>
                        <?php foreach ($tracksCollection->getItems() as $track) : ?>
                            <?php /** @var \Magento\Sales\Model\Order\Shipment\Track $track */ ?>
                            <?php if ($track->isCustom()): ?>
                                <?= $escaper->escapeHtml($track->getNumber()) ?>
                            <?php else: ?>
                                <a href="#"
                                   data-mage-init='{"popupWindow": {"windowURL":"<?= $escaper->escapeUrl($this->helper(Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($track)) ?>","windowName":"trackorder","width":800,"height":600,"left":0,"top":0,"resizable":1,"scrollbars":1}}'
                                   class="action track"><span><?= $escaper->escapeHtml($track->getNumber()) ?></span>
                                </a>
                            <?php endif; ?>
                            <?php if ($i != $_size): ?>, <?php endif; ?>
                            <?php $i++;
                        endforeach; ?>
                        <?php } ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= $escaper->escapeHtml(__('Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= $escaper->escapeHtml(__('Payment Method')) ?></span>
            </strong>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
